---
title: "KCpulseox"
author: "Katherine Choi"
date: "2022-10-11"
output: html_document
---

```{r setup, include=FALSE}
#https://www.rdocumentation.org/packages/bigrquery/versions/0.4.1
knitr::opts_chunk$set(echo = TRUE)

library(dslabs)
library(dplyr)
library(tidyverse)
library(bigrquery)
library(comorbidity)
library(dbplyr)
library(ggthemes)
library(pROC)
library(rmarkdown)
library(labelled)



select <- dplyr::select


options(scipen = 20)

con <- dbConnect(
  bigrquery::bigquery(),
  project = "hstpulseox",
  dataset = "physionet-data.mimiciv_derived",
  )

#bq_auth(email="bigquerytor@hstpulseox.iam.gserviceaccount.com")
#bq_auth(path= "/hstpulseox-5eceb4fb684e.json")
bq_auth(path= `~/Documents/Rrepo/pulseox/hstpulseox-21724c014c39.json`)


```

```{sql, connection=con, output.var = "spo2all",echo = FALSE}

SELECT subject_id, stay_id, charttime, resp_rate, spo2
FROM `physionet-data.mimiciv_derived.vitalsign`

```
```{sql, connection=con, output.var = "po2all",echo = FALSE}

SELECT subject_id, hadm_id, charttime, so2, po2, specimen
FROM `physionet-data.mimiciv_derived.bg`
WHERE specimen = "ART."

```
```{r}

combodata <- merge(po2all, spo2all, by = c("subject_id", "charttime"))
# inner join that keeps a row for each abg drawn result that has a spo2 with same subject_id

```


```{r}

filt_subjectids <- c(unique(combodata$subject_id))

```



# 19,795 unique subject ID's


# Create demographic table subject ID's


```{sql, connection=con, output.var = "icustaydetail",echo = FALSE}

SELECT *
FROM `physionet-data.mimiciv_derived.icustay_detail`
```


```{sql, connection=con, output.var = "age",echo = FALSE}
SELECT subject_id, hadm_id, age
FROM `physionet-data.mimiciv_derived.age`
```


```{r}
demographics <- left_join(icustaydetail, age, by=c("subject_id", "hadm_id"))

```


```{r}
subjectdemog <- subset(demographics, subject_id %in% filt_subjectids)

ggplot(subjectdemog, aes(x=age)) + geom_histogram(binwidth=5)

subjectdemog %>%
  group_by(group = cut(age, breaks = seq(0, max(age), 11))) %>%
  summarise(n = n())

subjectdemog %>% count(gender)

subjectdemog %>% 
  group_by(race) %>%
  summarise(n = n()) %>%
    mutate(Freq = n/sum(n))

ggplot(subjectdemog, aes(x=los_icu)) + geom_histogram(binwidth=1)



```




# Demographics of the cohort 
M/F
Race 
Age
Duration of stay in icu
Mean time on oxygen
Ph
Co2

# Compare demographics in patients with paired data avail, vs the raw population


# Compare demographics in patients with different deltas between pao2 and sao2


